{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "564ba3c5",
   "metadata": {},
   "outputs": [],
   "source": [
    "from icrawler.builtin import BingImageCrawler\n",
    "from configs.paths import WEB_DATASET_DIR\n",
    "import os\n",
    "\n",
    "def download_images(query, n, out_dir):\n",
    "    crawler = BingImageCrawler(storage={'root_dir': out_dir})\n",
    "    crawler.crawl(keyword=query, max_num=n)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8d429b38",
   "metadata": {},
   "outputs": [],
   "source": [
    "bushes = [\n",
    "    'чубушник',\n",
    "    \"лапчатка кустарниковая\",\n",
    "    \"сирень обыкновенная\",\n",
    "    \"карагана древовидная\",\n",
    "    \"пузыреплодник калинолистный\",\n",
    "    \"спирея\",\n",
    "    \"кизильник\",\n",
    "    \"дерен белый\",\n",
    "    \"лещина\",\n",
    "    \"боярышник\",\n",
    "    \"роза собачья\",\n",
    "    \"роза морщинистая\"\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2bf67c97",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-09-29 22:59:32,996 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 22:59:32,998 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 22:59:32,999 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 22:59:33,001 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 22:59:33,004 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 22:59:33,472 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст чубушник реальное фото&first=0\n",
      "2025-09-29 22:59:33,612 - ERROR - downloader - Exception caught when downloading file http://plodogorod.com/wp-content/uploads/2015/10/CHubushnik-kust-730x548.jpg, error: HTTPConnectionPool(host='plodogorod.com', port=80): Max retries exceeded with url: /wp-content/uploads/2015/10/CHubushnik-kust-730x548.jpg (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x000001E698EB4AF0>: Failed to resolve 'plodogorod.com' ([Errno 11002] getaddrinfo failed)\")), remaining retry times: 2\n",
      "2025-09-29 22:59:33,642 - ERROR - downloader - Exception caught when downloading file http://plodogorod.com/wp-content/uploads/2015/10/CHubushnik-kust-730x548.jpg, error: HTTPConnectionPool(host='plodogorod.com', port=80): Max retries exceeded with url: /wp-content/uploads/2015/10/CHubushnik-kust-730x548.jpg (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x000001E698EB4D90>: Failed to resolve 'plodogorod.com' ([Errno 11001] getaddrinfo failed)\")), remaining retry times: 1\n",
      "2025-09-29 22:59:33,647 - ERROR - downloader - Exception caught when downloading file http://plodogorod.com/wp-content/uploads/2015/10/CHubushnik-kust-730x548.jpg, error: HTTPConnectionPool(host='plodogorod.com', port=80): Max retries exceeded with url: /wp-content/uploads/2015/10/CHubushnik-kust-730x548.jpg (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x000001E698EB5300>: Failed to resolve 'plodogorod.com' ([Errno 11001] getaddrinfo failed)\")), remaining retry times: 0\n",
      "2025-09-29 22:59:40,456 - ERROR - downloader - Exception caught when downloading file https://rastenievod.com/wp-content/uploads/2017/05/4-10.jpg, error: HTTPSConnectionPool(host='rastenievod.com', port=443): Read timed out. (read timeout=5), remaining retry times: 2\n",
      "2025-09-29 22:59:45,463 - ERROR - downloader - Exception caught when downloading file https://rastenievod.com/wp-content/uploads/2017/05/4-10.jpg, error: HTTPSConnectionPool(host='rastenievod.com', port=443): Read timed out. (read timeout=5), remaining retry times: 1\n",
      "2025-09-29 22:59:50,490 - ERROR - downloader - Exception caught when downloading file https://rastenievod.com/wp-content/uploads/2017/05/4-10.jpg, error: HTTPSConnectionPool(host='rastenievod.com', port=443): Read timed out. (read timeout=5), remaining retry times: 0\n",
      "2025-09-29 22:59:50,986 - INFO - downloader - image #1\thttps://bigfoto.name/photo/uploads/posts/2023-02/1676907025_bigfoto-name-p-chubushnik-na-dache-19.jpg\n",
      "2025-09-29 22:59:51,118 - INFO - downloader - image #2\thttps://bigfoto.name/photo/uploads/posts/2023-02/1676907111_bigfoto-name-p-chubushnik-na-dache-12.jpg\n",
      "2025-09-29 22:59:51,361 - INFO - downloader - image #3\thttps://bigfoto.name/photo/uploads/posts/2023-02/1676907084_bigfoto-name-p-chubushnik-na-dache-11.jpg\n",
      "2025-09-29 22:59:56,377 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1627172886_12-p-zhasmin-chubushnik-v-landshaftnom-dizaine-13.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1627172886_12-p-zhasmin-chubushnik-v-landshaftnom-dizaine-13.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698EB60B0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:00:01,384 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1627172886_12-p-zhasmin-chubushnik-v-landshaftnom-dizaine-13.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1627172886_12-p-zhasmin-chubushnik-v-landshaftnom-dizaine-13.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F225C0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:00:06,394 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1627172886_12-p-zhasmin-chubushnik-v-landshaftnom-dizaine-13.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1627172886_12-p-zhasmin-chubushnik-v-landshaftnom-dizaine-13.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F22AD0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:00:06,533 - INFO - downloader - image #4\thttps://bigfoto.name/photo/uploads/posts/2023-02/1676907100_bigfoto-name-p-chubushnik-na-dache-53.jpg\n",
      "2025-09-29 23:00:06,648 - INFO - downloader - image #5\thttps://bigfoto.name/photo/uploads/posts/2023-02/1676907105_bigfoto-name-p-chubushnik-na-dache-62.jpg\n",
      "2025-09-29 23:00:11,676 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620331584_15-p-chubushnik-v-sadu-foto-15.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620331584_15-p-chubushnik-v-sadu-foto-15.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F22E90>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:00:16,694 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620331584_15-p-chubushnik-v-sadu-foto-15.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620331584_15-p-chubushnik-v-sadu-foto-15.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F23550>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:00:18,753 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:00:18,754 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:00:21,712 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620331584_15-p-chubushnik-v-sadu-foto-15.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620331584_15-p-chubushnik-v-sadu-foto-15.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F23A00>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:00:26,718 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637366940_3-pro-dachnikov-com-p-chubushnik-na-dachnom-uchastke-foto-3.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637366940_3-pro-dachnikov-com-p-chubushnik-na-dachnom-uchastke-foto-3.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69BF59F30>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:00:31,733 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637366940_3-pro-dachnikov-com-p-chubushnik-na-dachnom-uchastke-foto-3.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637366940_3-pro-dachnikov-com-p-chubushnik-na-dachnom-uchastke-foto-3.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698EB4460>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:00:36,752 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637366940_3-pro-dachnikov-com-p-chubushnik-na-dachnom-uchastke-foto-3.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637366940_3-pro-dachnikov-com-p-chubushnik-na-dachnom-uchastke-foto-3.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698EB5FF0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:00:41,759 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620331621_42-p-chubushnik-v-sadu-foto-44.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620331621_42-p-chubushnik-v-sadu-foto-44.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F23700>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:00:46,771 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620331621_42-p-chubushnik-v-sadu-foto-44.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620331621_42-p-chubushnik-v-sadu-foto-44.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F23010>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:00:51,786 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620331621_42-p-chubushnik-v-sadu-foto-44.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620331621_42-p-chubushnik-v-sadu-foto-44.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F21F00>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:00:56,791 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621449633_25-p-chubushnik-izgorod-28.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621449633_25-p-chubushnik-izgorod-28.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F226E0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:01:01,803 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621449633_25-p-chubushnik-izgorod-28.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621449633_25-p-chubushnik-izgorod-28.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C2BC190>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:01:06,812 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621449633_25-p-chubushnik-izgorod-28.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621449633_25-p-chubushnik-izgorod-28.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C2BC6A0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:01:11,830 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620331564_18-p-chubushnik-v-sadu-foto-18.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620331564_18-p-chubushnik-v-sadu-foto-18.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698EB5D80>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:01:16,840 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620331564_18-p-chubushnik-v-sadu-foto-18.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620331564_18-p-chubushnik-v-sadu-foto-18.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69BF5A2C0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:01:21,855 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620331564_18-p-chubushnik-v-sadu-foto-18.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620331564_18-p-chubushnik-v-sadu-foto-18.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F22470>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:01:22,221 - INFO - downloader - image #6\thttps://bigfoto.name/photo/uploads/posts/2023-02/1676907113_bigfoto-name-p-chubushnik-na-dache-59.jpg\n",
      "2025-09-29 23:01:27,226 - INFO - downloader - no more download task for thread downloader-001\n",
      "2025-09-29 23:01:27,226 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:01:28,177 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:01:28,179 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:01:28,180 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:01:28,180 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:01:28,182 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:01:28,184 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:01:28,601 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст лапчатка кустарниковая реальное фото&first=0\n",
      "2025-09-29 23:01:30,301 - INFO - downloader - image #1\thttps://media.decorateme.com/article2images/1987/lapchatka-kustarnikovaia.jpg\n",
      "2025-09-29 23:01:30,442 - INFO - downloader - image #2\thttp://cveti-rasteniya.ru/wp-content/gallery/lapchatka-kustarnikovaya/11.jpg\n",
      "2025-09-29 23:01:35,452 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1627002621_10-p-lapchatka-kustarnikovaya-v-landshaftnom-di-10.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1627002621_10-p-lapchatka-kustarnikovaya-v-landshaftnom-di-10.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C333940>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:01:40,459 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1627002621_10-p-lapchatka-kustarnikovaya-v-landshaftnom-di-10.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1627002621_10-p-lapchatka-kustarnikovaya-v-landshaftnom-di-10.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C333FD0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:01:45,470 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1627002621_10-p-lapchatka-kustarnikovaya-v-landshaftnom-di-10.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1627002621_10-p-lapchatka-kustarnikovaya-v-landshaftnom-di-10.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3332E0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:01:45,609 - INFO - downloader - image #3\thttps://www.art-landshaft.ru/uploadedFiles/eshopimages/big/lapchatka-abodsvud-1.jpg\n",
      "2025-09-29 23:01:45,735 - INFO - downloader - image #4\thttps://img.7dach.ru/image/1200/00/00/71/2019/06/27/c29f34.jpg\n",
      "2025-09-29 23:01:45,774 - ERROR - downloader - Exception caught when downloading file https://cdn.botanichka.ru/wp-content/uploads/2010/08/Pentaphylloides-fruticosa-6.jpg, error: HTTPSConnectionPool(host='cdn.botanichka.ru', port=443): Max retries exceeded with url: /wp-content/uploads/2010/08/Pentaphylloides-fruticosa-6.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))), remaining retry times: 2\n",
      "2025-09-29 23:01:45,805 - ERROR - downloader - Exception caught when downloading file https://cdn.botanichka.ru/wp-content/uploads/2010/08/Pentaphylloides-fruticosa-6.jpg, error: HTTPSConnectionPool(host='cdn.botanichka.ru', port=443): Max retries exceeded with url: /wp-content/uploads/2010/08/Pentaphylloides-fruticosa-6.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))), remaining retry times: 1\n",
      "2025-09-29 23:01:45,837 - ERROR - downloader - Exception caught when downloading file https://cdn.botanichka.ru/wp-content/uploads/2010/08/Pentaphylloides-fruticosa-6.jpg, error: HTTPSConnectionPool(host='cdn.botanichka.ru', port=443): Max retries exceeded with url: /wp-content/uploads/2010/08/Pentaphylloides-fruticosa-6.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))), remaining retry times: 0\n",
      "2025-09-29 23:01:50,849 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637356319_16-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-17.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637356319_16-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-17.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C385900>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:01:55,868 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637356319_16-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-17.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637356319_16-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-17.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C385E40>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:02:00,880 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637356319_16-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-17.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637356319_16-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-17.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3862F0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:02:00,942 - INFO - downloader - image #5\thttps://blumgarden.ru/wp-content/uploads/2018/12/lapchatka-kustarnikovaya-abbotsvud.jpg\n",
      "2025-09-29 23:02:05,950 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-09/1632704567_10-p-lapchatka-kustarnikovaya-izgorod-foto-11.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-09/1632704567_10-p-lapchatka-kustarnikovaya-izgorod-foto-11.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C333AC0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:02:09,019 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:02:09,020 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:02:10,954 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-09/1632704567_10-p-lapchatka-kustarnikovaya-izgorod-foto-11.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-09/1632704567_10-p-lapchatka-kustarnikovaya-izgorod-foto-11.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C385DE0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:02:15,966 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-09/1632704567_10-p-lapchatka-kustarnikovaya-izgorod-foto-11.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-09/1632704567_10-p-lapchatka-kustarnikovaya-izgorod-foto-11.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F237F0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:02:16,030 - INFO - downloader - image #6\thttps://img.7dach.ru/image/1200/17/79/12/2020/05/25/3f92b0.jpg\n",
      "2025-09-29 23:02:21,041 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620398993_59-p-lapchatka-na-klumbe-foto-69.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620398993_59-p-lapchatka-na-klumbe-foto-69.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3BC700>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:02:26,053 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620398993_59-p-lapchatka-na-klumbe-foto-69.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620398993_59-p-lapchatka-na-klumbe-foto-69.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3BC9A0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:02:31,062 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620398993_59-p-lapchatka-na-klumbe-foto-69.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620398993_59-p-lapchatka-na-klumbe-foto-69.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3BCEB0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:02:31,679 - INFO - downloader - image #7\thttps://s14.stc.all.kpcdn.net/family/wp-content/uploads/2023/05/top-v-lapchatka-kustarnikovaya-960x540-1.jpg\n",
      "2025-09-29 23:02:31,934 - INFO - downloader - image #8\thttps://s14.stc.all.kpcdn.net/family/wp-content/uploads/2023/05/photos-to-gallery-lapchatka-kustarnikovaya-02-725x483-1.jpg\n",
      "2025-09-29 23:02:36,952 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637356333_4-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-4.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637356333_4-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-4.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3BD390>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:02:41,970 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637356333_4-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-4.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637356333_4-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-4.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3BDBA0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:02:46,986 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637356333_4-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-4.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637356333_4-pro-dachnikov-com-p-lapchatka-kustarnikovaya-v-dizaine-sada-fo-4.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F23400>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:02:51,999 - INFO - downloader - no more download task for thread downloader-001\n",
      "2025-09-29 23:02:52,000 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:02:52,062 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:02:52,063 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:02:52,064 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:02:52,064 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:02:52,067 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:02:52,068 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:02:52,538 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст сирень обыкновенная реальное фото&first=0\n",
      "2025-09-29 23:02:57,578 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778815_34-p-foto-rasteniya-kust-sireni-47.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778815_34-p-foto-rasteniya-kust-sireni-47.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C332F20>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:03:02,593 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778815_34-p-foto-rasteniya-kust-sireni-47.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778815_34-p-foto-rasteniya-kust-sireni-47.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C332CE0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:03:07,603 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778815_34-p-foto-rasteniya-kust-sireni-47.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778815_34-p-foto-rasteniya-kust-sireni-47.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3328C0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:03:12,611 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778842_78-p-foto-rasteniya-kust-sireni-105.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778842_78-p-foto-rasteniya-kust-sireni-105.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3322C0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:03:17,624 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778842_78-p-foto-rasteniya-kust-sireni-105.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778842_78-p-foto-rasteniya-kust-sireni-105.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331F00>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:03:22,628 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778842_78-p-foto-rasteniya-kust-sireni-105.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778842_78-p-foto-rasteniya-kust-sireni-105.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331930>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:03:27,645 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778892_74-p-foto-rasteniya-kust-sireni-101.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778892_74-p-foto-rasteniya-kust-sireni-101.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331660>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:03:32,653 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778892_74-p-foto-rasteniya-kust-sireni-101.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778892_74-p-foto-rasteniya-kust-sireni-101.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331150>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:03:37,662 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778892_74-p-foto-rasteniya-kust-sireni-101.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778892_74-p-foto-rasteniya-kust-sireni-101.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331780>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:03:42,672 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778840_87-p-foto-rasteniya-kust-sireni-114.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778840_87-p-foto-rasteniya-kust-sireni-114.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331CF0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:03:47,678 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778840_87-p-foto-rasteniya-kust-sireni-114.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778840_87-p-foto-rasteniya-kust-sireni-114.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C332200>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:03:49,749 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:03:49,749 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:03:52,693 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778840_87-p-foto-rasteniya-kust-sireni-114.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778840_87-p-foto-rasteniya-kust-sireni-114.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3326B0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:03:57,699 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778784_20-p-foto-rasteniya-kust-sireni-29.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778784_20-p-foto-rasteniya-kust-sireni-29.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C333AC0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:04:02,707 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778784_20-p-foto-rasteniya-kust-sireni-29.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778784_20-p-foto-rasteniya-kust-sireni-29.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C332EC0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:04:07,724 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778784_20-p-foto-rasteniya-kust-sireni-29.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778784_20-p-foto-rasteniya-kust-sireni-29.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C330EE0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:04:12,740 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778809_43-p-foto-rasteniya-kust-sireni-64.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778809_43-p-foto-rasteniya-kust-sireni-64.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3308E0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:04:17,747 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778809_43-p-foto-rasteniya-kust-sireni-64.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778809_43-p-foto-rasteniya-kust-sireni-64.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C330220>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:04:22,751 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621778809_43-p-foto-rasteniya-kust-sireni-64.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621778809_43-p-foto-rasteniya-kust-sireni-64.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3300A0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:04:22,913 - INFO - downloader - image #1\thttps://herbana.world/media/zoo/images/aca529563aa15dc42326252373a69cb3_e1c75d962e8e747e00ec27434c6927f1.jpg\n",
      "2025-09-29 23:04:27,919 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623243873_52-p-foto-rasteniya-siren-derevo-59.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623243873_52-p-foto-rasteniya-siren-derevo-59.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C330700>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:04:32,926 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623243873_52-p-foto-rasteniya-siren-derevo-59.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623243873_52-p-foto-rasteniya-siren-derevo-59.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C330220>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:04:37,935 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623243873_52-p-foto-rasteniya-siren-derevo-59.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623243873_52-p-foto-rasteniya-siren-derevo-59.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331030>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:04:42,950 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623243897_12-p-foto-rasteniya-siren-derevo-16.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623243897_12-p-foto-rasteniya-siren-derevo-16.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C333010>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:04:47,966 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623243897_12-p-foto-rasteniya-siren-derevo-16.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623243897_12-p-foto-rasteniya-siren-derevo-16.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C333F10>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:04:52,985 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623243897_12-p-foto-rasteniya-siren-derevo-16.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623243897_12-p-foto-rasteniya-siren-derevo-16.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C332C20>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:04:57,988 - INFO - downloader - no more download task for thread downloader-001\n",
      "2025-09-29 23:04:57,988 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:04:58,313 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:04:58,315 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:04:58,315 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:04:58,316 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:04:58,318 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:04:58,319 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:04:58,741 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст карагана древовидная реальное фото&first=0\n",
      "2025-09-29 23:05:03,768 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621014170_17-p-karagana-drevovidnaya-foto-18.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621014170_17-p-karagana-drevovidnaya-foto-18.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C436140>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:05:08,774 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621014170_17-p-karagana-drevovidnaya-foto-18.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621014170_17-p-karagana-drevovidnaya-foto-18.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3BDF90>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:05:13,788 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621014170_17-p-karagana-drevovidnaya-foto-18.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621014170_17-p-karagana-drevovidnaya-foto-18.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E698F21DB0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:05:13,954 - INFO - downloader - image #1\thttps://www.flcity.ru/assets/images/resources/17325/img-20220920-103646-2.jpg\n",
      "2025-09-29 23:05:14,066 - INFO - downloader - image #2\thttps://planetaflora.ru/images/blog/карагана-1.jpg\n",
      "2025-09-29 23:05:15,055 - INFO - downloader - image #3\thttps://www.ruspitomniki.ru/upload/uf/dfa/zwa6t6i5uks7oa5k1byvyzcy0b6rud0m.jpg\n",
      "2025-09-29 23:05:20,062 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621014278_106-p-karagana-drevovidnaya-foto-114.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621014278_106-p-karagana-drevovidnaya-foto-114.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3319C0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:05:25,080 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621014278_106-p-karagana-drevovidnaya-foto-114.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621014278_106-p-karagana-drevovidnaya-foto-114.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C333C10>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:05:30,095 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621014278_106-p-karagana-drevovidnaya-foto-114.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621014278_106-p-karagana-drevovidnaya-foto-114.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C436680>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:05:30,136 - INFO - downloader - image #4\thttp://m-green.ru/img/work/nomencl/2857.jpg\n",
      "2025-09-29 23:05:32,043 - ERROR - downloader - Response status code 404, file https://viride.spb.ru/media/i/images/deciduous/419dcc7eef5a11ee9cc40242ac1a0006.jpg\n",
      "2025-09-29 23:05:32,205 - INFO - downloader - image #5\thttp://www.ruspitomniki.ru/upload/uf/220/3cihy5siph10q9yy9ewp1dpxki9xpmad.jpg\n",
      "2025-09-29 23:05:32,275 - INFO - downloader - image #6\thttps://wiki-dacha.ru/wp-content/uploads/2022/08/1.jpg\n",
      "2025-09-29 23:05:32,404 - INFO - downloader - image #7\thttp://www.ruspitomniki.ru/upload/uf/959/88bmu38l305337ftc2pzzsbu3axx5b3w.jpg\n",
      "2025-09-29 23:05:32,535 - INFO - downloader - image #8\thttps://zakazvsad.ru/wp-content/uploads/2022/06/caragana-arborescens-karagana-kupit-sazhenczy.jpg\n",
      "2025-09-29 23:05:32,640 - INFO - downloader - image #9\thttp://www.ruspitomniki.ru/upload/uf/016/ptfx7yrwh54xwt6uwvv1gwgzfsi5ht9v.jpg\n",
      "2025-09-29 23:05:32,715 - INFO - downloader - image #10\thttps://sadyprincessy.ru/wp-content/uploads/2020/03/akatsiya-zheltaya-karagana-drevovidnaya-caragana-1.jpg\n",
      "2025-09-29 23:05:32,806 - INFO - downloader - downloaded images reach max num, thread downloader-001 is ready to exit\n",
      "2025-09-29 23:05:32,807 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:05:33,660 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:05:33,661 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:05:33,663 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:05:33,664 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:05:33,665 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:05:33,667 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:05:34,112 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст пузыреплодник калинолистный реальное фото&first=0\n",
      "2025-09-29 23:05:34,656 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:05:34,656 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:05:39,139 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626997988_4-p-puzireplodnik-kalinolistnii-v-landshafte-4.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626997988_4-p-puzireplodnik-kalinolistnii-v-landshafte-4.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D4B7340>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:05:44,153 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626997988_4-p-puzireplodnik-kalinolistnii-v-landshafte-4.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626997988_4-p-puzireplodnik-kalinolistnii-v-landshafte-4.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331FC0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:05:49,167 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626997988_4-p-puzireplodnik-kalinolistnii-v-landshafte-4.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626997988_4-p-puzireplodnik-kalinolistnii-v-landshafte-4.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3319F0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:05:49,294 - INFO - downloader - image #1\thttps://www.art-landshaft.ru/uploadedFiles/eshopimages/big/puzyreplodnik-1.jpg\n",
      "2025-09-29 23:05:54,308 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-09/1632758926_138-p-puzireplodnik-kalinolistnii-zhivaya-izgoro-159.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-09/1632758926_138-p-puzireplodnik-kalinolistnii-zhivaya-izgoro-159.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D4B77F0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:05:59,329 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-09/1632758926_138-p-puzireplodnik-kalinolistnii-zhivaya-izgoro-159.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-09/1632758926_138-p-puzireplodnik-kalinolistnii-zhivaya-izgoro-159.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D4B7E80>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:06:04,341 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-09/1632758926_138-p-puzireplodnik-kalinolistnii-zhivaya-izgoro-159.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-09/1632758926_138-p-puzireplodnik-kalinolistnii-zhivaya-izgoro-159.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331EA0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:06:09,346 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626998064_5-p-puzireplodnik-kalinolistnii-v-landshafte-5.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626998064_5-p-puzireplodnik-kalinolistnii-v-landshafte-5.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C3325F0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:06:14,367 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626998064_5-p-puzireplodnik-kalinolistnii-v-landshafte-5.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626998064_5-p-puzireplodnik-kalinolistnii-v-landshafte-5.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D4B79A0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:06:19,382 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626998064_5-p-puzireplodnik-kalinolistnii-v-landshafte-5.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626998064_5-p-puzireplodnik-kalinolistnii-v-landshafte-5.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D4B7880>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:06:19,451 - INFO - downloader - image #2\thttps://dachadacha.com/images/2019-07-23/tyulad1.jpg\n",
      "2025-09-29 23:06:20,504 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:06:20,505 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:06:24,458 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626998054_1-p-puzireplodnik-kalinolistnii-v-landshafte-1.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626998054_1-p-puzireplodnik-kalinolistnii-v-landshafte-1.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D4B7430>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:06:29,473 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626998054_1-p-puzireplodnik-kalinolistnii-v-landshafte-1.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626998054_1-p-puzireplodnik-kalinolistnii-v-landshafte-1.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C436E00>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:06:34,487 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626998054_1-p-puzireplodnik-kalinolistnii-v-landshafte-1.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626998054_1-p-puzireplodnik-kalinolistnii-v-landshafte-1.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D4B7160>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:06:39,492 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637642432_4-pro-dachnikov-com-p-puzireplodnik-kalinolistnii-darts-gold-fot-4.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637642432_4-pro-dachnikov-com-p-puzireplodnik-kalinolistnii-darts-gold-fot-4.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5086D0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:06:44,507 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637642432_4-pro-dachnikov-com-p-puzireplodnik-kalinolistnii-darts-gold-fot-4.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637642432_4-pro-dachnikov-com-p-puzireplodnik-kalinolistnii-darts-gold-fot-4.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D508B50>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:06:49,510 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637642432_4-pro-dachnikov-com-p-puzireplodnik-kalinolistnii-darts-gold-fot-4.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637642432_4-pro-dachnikov-com-p-puzireplodnik-kalinolistnii-darts-gold-fot-4.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5090C0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:06:54,526 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626998067_36-p-puzireplodnik-kalinolistnii-v-landshafte-38.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626998067_36-p-puzireplodnik-kalinolistnii-v-landshafte-38.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5094B0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:06:59,545 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626998067_36-p-puzireplodnik-kalinolistnii-v-landshafte-38.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626998067_36-p-puzireplodnik-kalinolistnii-v-landshafte-38.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C436710>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:07:04,556 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626998067_36-p-puzireplodnik-kalinolistnii-v-landshafte-38.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626998067_36-p-puzireplodnik-kalinolistnii-v-landshafte-38.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D4B73A0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:07:04,649 - INFO - downloader - image #3\thttp://moysad48.com/wp-content/uploads/2021/02/5f58227b1eb5b.jpg\n",
      "2025-09-29 23:07:09,663 - INFO - downloader - no more download task for thread downloader-001\n",
      "2025-09-29 23:07:09,663 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:07:09,710 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:07:09,713 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:07:09,714 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:07:09,716 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:07:09,718 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:07:09,719 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:07:10,115 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст спирея реальное фото&first=0\n",
      "2025-09-29 23:07:10,537 - INFO - downloader - image #1\thttps://tutknow.ru/uploads/posts/2017-10/1509282790_spireya-kak-vyraschivat-i-razmnozhat-na-svoem-uchastke.jpg\n",
      "2025-09-29 23:07:10,803 - INFO - downloader - image #2\thttps://www.irecommend.ru/sites/default/files/imagecache/copyright1/user-images/144305/irRj1LEtjA4zYyxuHnjXQ.jpg\n",
      "2025-09-29 23:07:11,094 - INFO - downloader - image #3\thttps://lanshaft.com/wp-content/uploads/2020/03/c5ef125328aa3a5fef0bf738e29378a9.jpg\n",
      "2025-09-29 23:07:11,285 - INFO - downloader - image #4\thttps://cveti-rasteniya.ru/wp-content/uploads/2016/08/12.jpg\n",
      "2025-09-29 23:07:11,333 - INFO - downloader - image #5\thttps://lafoy.ru/photo_l/spireya-foto-743-30797.jpg\n",
      "2025-09-29 23:07:11,365 - INFO - downloader - image #6\thttp://myflo.ru/img/spireja_4.jpg\n",
      "2025-09-29 23:07:11,697 - INFO - downloader - image #7\thttps://moneystrategy.ru/wp-content/uploads/2/f/2/2f2c743be2d22b6a4828b2e3a9b6652a.jpg\n",
      "2025-09-29 23:07:11,810 - INFO - downloader - image #8\thttps://www.irecommend.ru/sites/default/files/imagecache/copyright1/user-images/144305/R69vO3vG8zpdkjc69wg.jpg\n",
      "2025-09-29 23:07:16,816 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623279688_50-p-foto-rasteniya-spireya-ivolistnaya-kustarn-52.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623279688_50-p-foto-rasteniya-spireya-ivolistnaya-kustarn-52.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C437C70>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:07:21,821 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623279688_50-p-foto-rasteniya-spireya-ivolistnaya-kustarn-52.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623279688_50-p-foto-rasteniya-spireya-ivolistnaya-kustarn-52.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C437760>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:07:26,833 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623279688_50-p-foto-rasteniya-spireya-ivolistnaya-kustarn-52.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623279688_50-p-foto-rasteniya-spireya-ivolistnaya-kustarn-52.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C437CD0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:07:31,840 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1638041970_31-pro-dachnikov-com-p-kustarnik-spireya-foto-32.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1638041970_31-pro-dachnikov-com-p-kustarnik-spireya-foto-32.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D575780>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:07:36,849 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1638041970_31-pro-dachnikov-com-p-kustarnik-spireya-foto-32.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1638041970_31-pro-dachnikov-com-p-kustarnik-spireya-foto-32.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5759F0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:07:41,860 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1638041970_31-pro-dachnikov-com-p-kustarnik-spireya-foto-32.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1638041970_31-pro-dachnikov-com-p-kustarnik-spireya-foto-32.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D575F90>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:07:42,372 - INFO - downloader - image #9\thttps://cdnn21.img.ria.ru/images/07e6/05/05/1787022004_0:0:2965:2048_1920x0_80_0_0_249b513ae628e928133cbca5bea3d081.jpg\n",
      "2025-09-29 23:07:43,866 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:07:43,867 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:07:47,384 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1638041975_32-pro-dachnikov-com-p-kustarnik-spireya-foto-33.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1638041975_32-pro-dachnikov-com-p-kustarnik-spireya-foto-33.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C436B30>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:07:52,400 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1638041975_32-pro-dachnikov-com-p-kustarnik-spireya-foto-33.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1638041975_32-pro-dachnikov-com-p-kustarnik-spireya-foto-33.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331C00>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:07:57,409 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1638041975_32-pro-dachnikov-com-p-kustarnik-spireya-foto-33.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1638041975_32-pro-dachnikov-com-p-kustarnik-spireya-foto-33.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C436830>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:07:57,565 - INFO - downloader - image #10\thttps://orchardo.ru/wp-content/uploads/2019/05/post_5ce5990c34fba.jpg\n",
      "2025-09-29 23:07:57,782 - INFO - downloader - downloaded images reach max num, thread downloader-001 is ready to exit\n",
      "2025-09-29 23:07:57,783 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:07:58,238 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:07:58,241 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:07:58,243 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:07:58,244 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:07:58,247 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:07:58,252 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:07:58,673 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст кизильник реальное фото&first=0\n",
      "2025-09-29 23:08:03,704 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-04/1619402366_10-p-na-uchastke-kizilnik-blestyashchii-zhivaya-10.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-04/1619402366_10-p-na-uchastke-kizilnik-blestyashchii-zhivaya-10.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D46BB80>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:08:08,716 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-04/1619402366_10-p-na-uchastke-kizilnik-blestyashchii-zhivaya-10.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-04/1619402366_10-p-na-uchastke-kizilnik-blestyashchii-zhivaya-10.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D46BD30>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:08:13,729 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-04/1619402366_10-p-na-uchastke-kizilnik-blestyashchii-zhivaya-10.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-04/1619402366_10-p-na-uchastke-kizilnik-blestyashchii-zhivaya-10.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F0100>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:08:18,744 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637373691_71-pro-dachnikov-com-p-kizilnik-blestyashchii-cotoneaster-lucidus-76.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637373691_71-pro-dachnikov-com-p-kizilnik-blestyashchii-cotoneaster-lucidus-76.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C331E40>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:08:23,760 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637373691_71-pro-dachnikov-com-p-kizilnik-blestyashchii-cotoneaster-lucidus-76.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637373691_71-pro-dachnikov-com-p-kizilnik-blestyashchii-cotoneaster-lucidus-76.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D46BDC0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:08:28,768 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637373691_71-pro-dachnikov-com-p-kizilnik-blestyashchii-cotoneaster-lucidus-76.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637373691_71-pro-dachnikov-com-p-kizilnik-blestyashchii-cotoneaster-lucidus-76.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D46BA00>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:08:29,472 - INFO - downloader - image #1\thttps://pibig.info/uploads/posts/2022-11/1668686875_48-pibig-info-p-kizilnik-kustarnik-vkontakte-55.jpg\n",
      "2025-09-29 23:08:34,485 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351676_44-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-48.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351676_44-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-48.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F0040>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:08:39,496 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351676_44-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-48.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351676_44-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-48.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F0E80>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:08:44,503 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351676_44-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-48.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351676_44-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-48.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F1390>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:08:44,947 - INFO - downloader - image #2\thttps://bigfoto.name/photo/uploads/posts/2024-03/1709373441_bigfoto-name-p-kizilnik-blestyashchii-v-landshaftnom-diza-105.jpg\n",
      "2025-09-29 23:08:45,079 - INFO - downloader - image #3\thttps://pibig.info/uploads/posts/2022-11/1668686868_13-pibig-info-p-kizilnik-kustarnik-vkontakte-16.jpg\n",
      "2025-09-29 23:08:46,512 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:08:46,513 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:08:50,092 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351633_49-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-53.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351633_49-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-53.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F1A20>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:08:55,099 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351633_49-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-53.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351633_49-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-53.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D575540>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:09:00,110 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351633_49-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-53.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351633_49-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-53.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F1A50>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:09:05,126 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351624_2-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-2.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351624_2-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-2.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F20E0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:09:10,142 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351624_2-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-2.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351624_2-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-2.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F2500>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:09:15,158 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351624_2-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-2.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351624_2-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-2.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D575CF0>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:09:20,162 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623304143_20-p-foto-rasteniya-kizilnik-stokgolm-24.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623304143_20-p-foto-rasteniya-kizilnik-stokgolm-24.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D46BD00>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:09:25,178 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623304143_20-p-foto-rasteniya-kizilnik-stokgolm-24.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623304143_20-p-foto-rasteniya-kizilnik-stokgolm-24.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D46BF10>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:09:30,185 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623304143_20-p-foto-rasteniya-kizilnik-stokgolm-24.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623304143_20-p-foto-rasteniya-kizilnik-stokgolm-24.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D4B4BB0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:09:35,189 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351670_40-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-44.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351670_40-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-44.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F2200>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:09:40,193 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351670_40-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-44.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351670_40-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-44.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F0C40>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:09:45,206 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-11/1637351670_40-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-44.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-11/1637351670_40-pro-dachnikov-com-p-kizilnik-blestyashchii-kust-foto-44.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F1180>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:09:50,217 - INFO - downloader - no more download task for thread downloader-001\n",
      "2025-09-29 23:09:50,218 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:09:50,327 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:09:50,328 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:09:50,329 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:09:50,330 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:09:50,332 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:09:50,333 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:09:50,781 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст дерен белый реальное фото&first=0\n",
      "2025-09-29 23:09:55,820 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626997530_50-p-deren-belii-v-landshaftnom-dizaine-51.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626997530_50-p-deren-belii-v-landshaftnom-dizaine-51.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D577310>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:10:00,840 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626997530_50-p-deren-belii-v-landshaftnom-dizaine-51.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626997530_50-p-deren-belii-v-landshaftnom-dizaine-51.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D577130>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:10:05,845 - ERROR - downloader - Exception caught when downloading file https://pro-dachnikov.com/uploads/posts/2021-07/1626997530_50-p-deren-belii-v-landshaftnom-dizaine-51.jpg, error: HTTPSConnectionPool(host='pro-dachnikov.com', port=443): Max retries exceeded with url: /uploads/posts/2021-07/1626997530_50-p-deren-belii-v-landshaftnom-dizaine-51.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D575E70>, 'Connection to pro-dachnikov.com timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:10:05,972 - INFO - downloader - image #1\thttp://sazhaemvsadu.ru/wp-content/uploads/2013/04/Дерен-белый.jpg\n",
      "2025-09-29 23:10:06,018 - INFO - downloader - image #2\thttps://rastenievod.com/wp-content/uploads/2019/10/1-4.jpg\n",
      "2025-09-29 23:10:06,122 - INFO - downloader - image #3\thttps://www.venev1.ru/storage/media/10105/conversions/39_dyoren-list_wiki.jpg\n",
      "2025-09-29 23:10:06,245 - INFO - downloader - image #4\thttps://101klumba.ru/wp-content/uploads/2021/09/deren-belyj.jpg\n",
      "2025-09-29 23:10:12,190 - ERROR - downloader - Exception caught when downloading file https://pitomnik.kiev.ua/images/virtuemart/product/watermark/deren_beliy_elegantissima-07.jpg, error: HTTPSConnectionPool(host='pitomnik.kiev.ua', port=443): Max retries exceeded with url: /images/virtuemart/product/watermark/deren_beliy_elegantissima-07.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D576E30>, 'Connection to pitomnik.kiev.ua timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:10:17,206 - ERROR - downloader - Exception caught when downloading file https://pitomnik.kiev.ua/images/virtuemart/product/watermark/deren_beliy_elegantissima-07.jpg, error: HTTPSConnectionPool(host='pitomnik.kiev.ua', port=443): Max retries exceeded with url: /images/virtuemart/product/watermark/deren_beliy_elegantissima-07.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D576050>, 'Connection to pitomnik.kiev.ua timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:10:22,214 - ERROR - downloader - Exception caught when downloading file https://pitomnik.kiev.ua/images/virtuemart/product/watermark/deren_beliy_elegantissima-07.jpg, error: HTTPSConnectionPool(host='pitomnik.kiev.ua', port=443): Max retries exceeded with url: /images/virtuemart/product/watermark/deren_beliy_elegantissima-07.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D575D80>, 'Connection to pitomnik.kiev.ua timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:10:22,370 - INFO - downloader - image #5\thttps://www.ruspitomniki.ru/upload/uf/d78/nl127m8rdm008c1ju2g11bxy1c9ehea4.jpg\n",
      "2025-09-29 23:10:22,791 - INFO - downloader - image #6\thttps://bigfoto.name/photo/uploads/posts/2024-03/1710993977_bigfoto-name-ladt-p-kustarnik-dern-v-landshaftnom-dizaine-19.jpg\n",
      "2025-09-29 23:10:27,797 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623260489_17-p-foto-rasteniya-deren-belookaimlennii-19.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623260489_17-p-foto-rasteniya-deren-belookaimlennii-19.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F0670>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:10:30,851 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:10:30,852 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:10:32,800 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623260489_17-p-foto-rasteniya-deren-belookaimlennii-19.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623260489_17-p-foto-rasteniya-deren-belookaimlennii-19.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F0460>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:10:37,813 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1623260489_17-p-foto-rasteniya-deren-belookaimlennii-19.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1623260489_17-p-foto-rasteniya-deren-belookaimlennii-19.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D46BE50>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:10:37,880 - INFO - downloader - image #7\thttps://fb.ru/misc/i/gallery/31656/2310616.jpg\n",
      "2025-09-29 23:10:37,941 - INFO - downloader - image #8\thttps://www.greeninfo.ru/img/work/catalog/173_30477_big.jpg\n",
      "2025-09-29 23:10:38,048 - INFO - downloader - image #9\thttps://bigfoto.name/photo/uploads/posts/2024-03/1710993946_bigfoto-name-lgmd-p-kustarnik-dern-v-landshaftnom-dizaine-48.jpg\n",
      "2025-09-29 23:10:43,061 - ERROR - downloader - Exception caught when downloading file https://pitomnik.kiev.ua/images/virtuemart/product/watermark/deren_beliy_elegantissima02.jpg, error: HTTPSConnectionPool(host='pitomnik.kiev.ua', port=443): Max retries exceeded with url: /images/virtuemart/product/watermark/deren_beliy_elegantissima02.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5777F0>, 'Connection to pitomnik.kiev.ua timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:10:48,070 - ERROR - downloader - Exception caught when downloading file https://pitomnik.kiev.ua/images/virtuemart/product/watermark/deren_beliy_elegantissima02.jpg, error: HTTPSConnectionPool(host='pitomnik.kiev.ua', port=443): Max retries exceeded with url: /images/virtuemart/product/watermark/deren_beliy_elegantissima02.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F01F0>, 'Connection to pitomnik.kiev.ua timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:10:53,082 - ERROR - downloader - Exception caught when downloading file https://pitomnik.kiev.ua/images/virtuemart/product/watermark/deren_beliy_elegantissima02.jpg, error: HTTPSConnectionPool(host='pitomnik.kiev.ua', port=443): Max retries exceeded with url: /images/virtuemart/product/watermark/deren_beliy_elegantissima02.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F2BC0>, 'Connection to pitomnik.kiev.ua timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:10:53,220 - INFO - downloader - image #10\thttps://www.art-landshaft.ru/uploadedFiles/eshopimages/big/db2.jpg\n",
      "2025-09-29 23:10:58,235 - INFO - downloader - no more download task for thread downloader-001\n",
      "2025-09-29 23:10:58,236 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:10:59,050 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:10:59,052 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:10:59,053 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:10:59,054 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:10:59,056 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:10:59,057 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:10:59,494 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст лещина реальное фото&first=0\n",
      "2025-09-29 23:11:04,512 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022210_63-p-leshchina-foto-74.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022210_63-p-leshchina-foto-74.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A1A80>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:11:09,524 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022210_63-p-leshchina-foto-74.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022210_63-p-leshchina-foto-74.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A1CC0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:11:14,534 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022210_63-p-leshchina-foto-74.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022210_63-p-leshchina-foto-74.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A2110>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:11:19,543 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022245_66-p-leshchina-foto-77.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022245_66-p-leshchina-foto-77.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A25C0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:11:24,552 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022245_66-p-leshchina-foto-77.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022245_66-p-leshchina-foto-77.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A2AA0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:11:29,561 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022245_66-p-leshchina-foto-77.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022245_66-p-leshchina-foto-77.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A2F20>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:11:34,573 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620401244_69-p-leshchina-krasnolistnaya-foto-78.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620401244_69-p-leshchina-krasnolistnaya-foto-78.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D575F30>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:11:39,585 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620401244_69-p-leshchina-krasnolistnaya-foto-78.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620401244_69-p-leshchina-krasnolistnaya-foto-78.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D577670>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:11:44,595 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620401244_69-p-leshchina-krasnolistnaya-foto-78.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620401244_69-p-leshchina-krasnolistnaya-foto-78.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D576C50>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:11:49,609 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620967695_9-p-leshchina-drevovidnaya-foto-10.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620967695_9-p-leshchina-drevovidnaya-foto-10.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D46BA60>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:11:54,616 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620967695_9-p-leshchina-drevovidnaya-foto-10.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620967695_9-p-leshchina-drevovidnaya-foto-10.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D4B7E80>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:11:56,724 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:11:56,725 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:11:59,634 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620967695_9-p-leshchina-drevovidnaya-foto-10.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620967695_9-p-leshchina-drevovidnaya-foto-10.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F06A0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:12:04,639 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022240_101-p-leshchina-foto-113.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022240_101-p-leshchina-foto-113.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D576E00>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:12:09,653 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022240_101-p-leshchina-foto-113.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022240_101-p-leshchina-foto-113.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F23B0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:12:14,669 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022240_101-p-leshchina-foto-113.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022240_101-p-leshchina-foto-113.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A14B0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:12:19,684 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022240_32-p-leshchina-foto-39.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022240_32-p-leshchina-foto-39.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A2DD0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:12:24,690 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022240_32-p-leshchina-foto-39.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022240_32-p-leshchina-foto-39.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A2560>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:12:29,712 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022240_32-p-leshchina-foto-39.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022240_32-p-leshchina-foto-39.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F2CB0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:12:34,732 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022201_1-p-leshchina-foto-1.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022201_1-p-leshchina-foto-1.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F06A0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:12:39,751 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022201_1-p-leshchina-foto-1.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022201_1-p-leshchina-foto-1.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5F27D0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:12:44,757 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022201_1-p-leshchina-foto-1.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022201_1-p-leshchina-foto-1.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69C4379D0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:12:49,773 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620401221_60-p-leshchina-krasnolistnaya-foto-68.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620401221_60-p-leshchina-krasnolistnaya-foto-68.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D575ED0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:12:54,789 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620401221_60-p-leshchina-krasnolistnaya-foto-68.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620401221_60-p-leshchina-krasnolistnaya-foto-68.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D576290>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:12:59,804 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620401221_60-p-leshchina-krasnolistnaya-foto-68.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620401221_60-p-leshchina-krasnolistnaya-foto-68.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D575A80>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:13:04,811 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022239_6-p-leshchina-foto-7.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022239_6-p-leshchina-foto-7.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D5765F0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:13:09,831 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022239_6-p-leshchina-foto-7.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022239_6-p-leshchina-foto-7.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A2110>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:13:14,848 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621022239_6-p-leshchina-foto-7.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621022239_6-p-leshchina-foto-7.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D576CB0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:13:19,862 - INFO - downloader - no more download task for thread downloader-001\n",
      "2025-09-29 23:13:19,863 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:13:20,142 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:13:20,143 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:13:20,144 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:13:20,145 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:13:20,147 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:13:20,149 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:13:20,757 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст боярышник реальное фото&first=0\n",
      "2025-09-29 23:13:21,119 - INFO - downloader - image #1\thttps://dachadacha.com/images/2020-04-08/boyaryshnik-krupnoplodnyj.jpg\n",
      "2025-09-29 23:13:26,131 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747509_24-p-foto-rasteniya-boyarishnik-derevo-29.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747509_24-p-foto-rasteniya-boyarishnik-derevo-29.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D770790>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:13:31,136 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747509_24-p-foto-rasteniya-boyarishnik-derevo-29.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747509_24-p-foto-rasteniya-boyarishnik-derevo-29.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D771030>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:13:36,152 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747509_24-p-foto-rasteniya-boyarishnik-derevo-29.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747509_24-p-foto-rasteniya-boyarishnik-derevo-29.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D771510>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:13:41,158 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1624981677_42-p-boyarishnik-v-landshaftnom-dizaine-foto-44.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1624981677_42-p-boyarishnik-v-landshaftnom-dizaine-foto-44.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D7719C0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:13:46,167 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1624981677_42-p-boyarishnik-v-landshaftnom-dizaine-foto-44.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1624981677_42-p-boyarishnik-v-landshaftnom-dizaine-foto-44.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D771E70>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:13:51,186 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-06/1624981677_42-p-boyarishnik-v-landshaftnom-dizaine-foto-44.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-06/1624981677_42-p-boyarishnik-v-landshaftnom-dizaine-foto-44.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D770EB0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:13:56,202 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747495_20-p-foto-rasteniya-boyarishnik-derevo-25.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747495_20-p-foto-rasteniya-boyarishnik-derevo-25.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D7708E0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:14:01,218 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747495_20-p-foto-rasteniya-boyarishnik-derevo-25.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747495_20-p-foto-rasteniya-boyarishnik-derevo-25.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D771ED0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:14:06,228 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747495_20-p-foto-rasteniya-boyarishnik-derevo-25.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747495_20-p-foto-rasteniya-boyarishnik-derevo-25.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D772380>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:14:11,237 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747518_79-p-foto-rasteniya-boyarishnik-derevo-94.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747518_79-p-foto-rasteniya-boyarishnik-derevo-94.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D772830>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:14:14,260 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:14:14,261 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:14:16,246 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747518_79-p-foto-rasteniya-boyarishnik-derevo-94.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747518_79-p-foto-rasteniya-boyarishnik-derevo-94.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D772CE0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:14:21,254 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747518_79-p-foto-rasteniya-boyarishnik-derevo-94.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747518_79-p-foto-rasteniya-boyarishnik-derevo-94.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D577070>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:14:26,272 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620992115_25-p-boyarishnik-obiknovennii-foto-30.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620992115_25-p-boyarishnik-obiknovennii-foto-30.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D773070>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:14:31,278 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620992115_25-p-boyarishnik-obiknovennii-foto-30.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620992115_25-p-boyarishnik-obiknovennii-foto-30.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D7733A0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:14:36,296 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620992115_25-p-boyarishnik-obiknovennii-foto-30.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620992115_25-p-boyarishnik-obiknovennii-foto-30.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D7738B0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:14:41,311 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747533_39-p-foto-rasteniya-boyarishnik-derevo-46.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747533_39-p-foto-rasteniya-boyarishnik-derevo-46.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D577070>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:14:46,318 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747533_39-p-foto-rasteniya-boyarishnik-derevo-46.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747533_39-p-foto-rasteniya-boyarishnik-derevo-46.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D7738E0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:14:51,322 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621747533_39-p-foto-rasteniya-boyarishnik-derevo-46.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621747533_39-p-foto-rasteniya-boyarishnik-derevo-46.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D773580>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:14:52,085 - INFO - downloader - image #2\thttp://rasfokus.ru/images/photos/medium/9f93e624724f69483e72dec9b9729ad0.jpg\n",
      "2025-09-29 23:14:57,100 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620326319_24-p-boyarishnik-krasivotsvetushchii-foto-26.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620326319_24-p-boyarishnik-krasivotsvetushchii-foto-26.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D772E00>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:15:02,107 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620326319_24-p-boyarishnik-krasivotsvetushchii-foto-26.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620326319_24-p-boyarishnik-krasivotsvetushchii-foto-26.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D772980>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:15:07,117 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1620326319_24-p-boyarishnik-krasivotsvetushchii-foto-26.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1620326319_24-p-boyarishnik-krasivotsvetushchii-foto-26.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D7724A0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:15:08,048 - INFO - downloader - image #3\thttps://pibig.info/uploads/posts/2022-11/1669315938_25-pibig-info-p-boyarishnik-kust-krasivo-26.jpg\n",
      "2025-09-29 23:15:13,062 - INFO - downloader - no more download task for thread downloader-001\n",
      "2025-09-29 23:15:13,063 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:15:13,862 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:15:13,863 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:15:13,865 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:15:13,866 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:15:13,869 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:15:13,870 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:15:14,548 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст роза собачья реальное фото&first=0\n",
      "2025-09-29 23:15:19,580 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621044074_108-p-shipovnik-sobachii-foto-114.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621044074_108-p-shipovnik-sobachii-foto-114.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D46BF70>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:15:24,596 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621044074_108-p-shipovnik-sobachii-foto-114.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621044074_108-p-shipovnik-sobachii-foto-114.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A3F70>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:15:29,608 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621044074_108-p-shipovnik-sobachii-foto-114.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621044074_108-p-shipovnik-sobachii-foto-114.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A3A90>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:15:30,014 - INFO - downloader - image #1\thttps://i.pinimg.com/originals/14/c7/bf/14c7bf9f56ce62bbc5ed6037dbb3409f.jpg\n",
      "2025-09-29 23:15:30,558 - INFO - downloader - image #2\thttps://storage.needpix.com/rsynced_images/wild-rose-2395123_1280.jpg\n",
      "2025-09-29 23:15:31,130 - INFO - downloader - image #3\thttps://centrosad.ru/1891-medium_0rozasobachjarosacaninajpg/roza-sobachja-rosa-canina.jpg\n",
      "2025-09-29 23:15:31,628 - INFO - downloader - image #4\thttps://upload.rozoteka.ru/4G2kSy9y-H/image.jpg\n",
      "2025-09-29 23:15:32,134 - INFO - downloader - image #5\thttps://yaposad.ru/wp-content/uploads/2023/11/shipovnik-roza-sobachia-opisanie-osobennosti-sorta-yhod-i-razmnojenie_1.jpg\n",
      "2025-09-29 23:15:32,618 - INFO - downloader - image #6\thttps://zvetki.ru/bfimage/122_353.jpg\n",
      "2025-09-29 23:15:33,593 - INFO - downloader - image #7\thttps://klau.club/uploads/posts/2023-02/1677164368_klau-club-p-vidi-rozotsvetnikh-rastenii-oboi-22.jpg\n",
      "2025-09-29 23:15:38,598 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621044132_58-p-shipovnik-sobachii-foto-60.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621044132_58-p-shipovnik-sobachii-foto-60.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A1E40>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 2\n",
      "2025-09-29 23:15:43,608 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621044132_58-p-shipovnik-sobachii-foto-60.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621044132_58-p-shipovnik-sobachii-foto-60.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D6A13C0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 1\n",
      "2025-09-29 23:15:48,625 - ERROR - downloader - Exception caught when downloading file https://na-dache.pro/uploads/posts/2021-05/1621044132_58-p-shipovnik-sobachii-foto-60.jpg, error: HTTPSConnectionPool(host='na-dache.pro', port=443): Max retries exceeded with url: /uploads/posts/2021-05/1621044132_58-p-shipovnik-sobachii-foto-60.jpg (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E69D46B8B0>, 'Connection to na-dache.pro timed out. (connect timeout=5)')), remaining retry times: 0\n",
      "2025-09-29 23:15:48,928 - INFO - downloader - image #8\thttps://www.astrasad.ru/img/work/nomencl/a_11151_841.jpg\n",
      "2025-09-29 23:15:49,231 - INFO - downloader - image #9\thttps://greenpoint24.ru/image/cache/catalog/62-720x720_0.jpg\n",
      "2025-09-29 23:15:50,000 - INFO - downloader - image #10\thttp://www.ruspitomniki.ru/upload/uf/07c/c6gypgx8oc8xfdv3nsadeirum4u9gvus.jpg\n",
      "2025-09-29 23:15:50,943 - INFO - parser - no more page urls for thread parser-001 to parse\n",
      "2025-09-29 23:15:50,944 - INFO - parser - thread parser-001 exit\n",
      "2025-09-29 23:15:51,121 - INFO - downloader - downloaded images reach max num, thread downloader-001 is ready to exit\n",
      "2025-09-29 23:15:51,122 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:15:52,118 - INFO - icrawler.crawler - Crawling task done!\n",
      "2025-09-29 23:15:52,121 - INFO - icrawler.crawler - start crawling...\n",
      "2025-09-29 23:15:52,122 - INFO - icrawler.crawler - starting 1 feeder threads...\n",
      "2025-09-29 23:15:52,124 - INFO - feeder - thread feeder-001 exit\n",
      "2025-09-29 23:15:52,126 - INFO - icrawler.crawler - starting 1 parser threads...\n",
      "2025-09-29 23:15:52,128 - INFO - icrawler.crawler - starting 1 downloader threads...\n",
      "2025-09-29 23:15:52,748 - INFO - parser - parsing result page https://www.bing.com/images/async?q=куст роза морщинистая реальное фото&first=0\n",
      "2025-09-29 23:15:53,324 - INFO - downloader - image #1\thttps://www.ruspitomniki.ru/upload/uf/ea0/rekzm5qgq38xgia0z3dnchjmrkffi4pm.jpg\n",
      "2025-09-29 23:15:53,748 - INFO - downloader - image #2\thttps://st44.stpulscen.ru/images/product/237/381/085_big.jpg\n",
      "2025-09-29 23:15:53,861 - ERROR - downloader - Exception caught when downloading file https://cdn.botanichka.ru/wp-content/uploads/2010/04/rosa-7-03-1068x712.jpg, error: HTTPSConnectionPool(host='cdn.botanichka.ru', port=443): Max retries exceeded with url: /wp-content/uploads/2010/04/rosa-7-03-1068x712.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))), remaining retry times: 2\n",
      "2025-09-29 23:15:53,945 - ERROR - downloader - Exception caught when downloading file https://cdn.botanichka.ru/wp-content/uploads/2010/04/rosa-7-03-1068x712.jpg, error: HTTPSConnectionPool(host='cdn.botanichka.ru', port=443): Max retries exceeded with url: /wp-content/uploads/2010/04/rosa-7-03-1068x712.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))), remaining retry times: 1\n",
      "2025-09-29 23:15:54,027 - ERROR - downloader - Exception caught when downloading file https://cdn.botanichka.ru/wp-content/uploads/2010/04/rosa-7-03-1068x712.jpg, error: HTTPSConnectionPool(host='cdn.botanichka.ru', port=443): Max retries exceeded with url: /wp-content/uploads/2010/04/rosa-7-03-1068x712.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))), remaining retry times: 0\n",
      "2025-09-29 23:15:54,356 - INFO - downloader - image #3\thttps://www.astrasad.ru/img/work/nomencl/roza-morschinistaya-khansa-3507.jpg\n",
      "2025-09-29 23:15:54,701 - INFO - downloader - image #4\thttp://1decor.org/wp-content/uploads/2017/05/Roza-morshhinistaja2.jpg\n",
      "2025-09-29 23:15:55,022 - INFO - downloader - image #5\thttps://www.greeninfo.ru/img/work/catalog/677_29773_big.jpg\n",
      "2025-09-29 23:15:55,514 - INFO - downloader - image #6\thttps://irecommend.ru/sites/default/files/imagecache/copyright1/user-images/1170317/fSlXP3d5ahUSEfXBMn5Lg.jpg\n",
      "2025-09-29 23:15:55,994 - INFO - downloader - image #7\thttps://chelpitomnik.ru/wp-content/uploads/2018/09/Roza-morshhinistaya.jpg\n",
      "2025-09-29 23:15:56,416 - INFO - downloader - image #8\thttp://www.ruspitomniki.ru/upload/resize_cache/uf/48a/556_556_2/mykwg1j5i3bhzxy3nhnlkb3z2ry731x6.jpg\n",
      "2025-09-29 23:15:56,817 - INFO - downloader - image #9\thttps://www.rosselhozpitomnik.ru/upload/610/988/rosa_morshinistya5.jpg\n",
      "2025-09-29 23:15:57,181 - INFO - downloader - image #10\thttps://fittonia.ru/wa-data/public/shop/products/35/12/1235/images/2044/2044.970x970.jpg\n",
      "2025-09-29 23:15:57,531 - INFO - downloader - downloaded images reach max num, thread downloader-001 is ready to exit\n",
      "2025-09-29 23:15:57,532 - INFO - downloader - thread downloader-001 exit\n",
      "2025-09-29 23:15:58,162 - INFO - icrawler.crawler - Crawling task done!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-09-29 23:15:58,193 - INFO - parser - downloaded image reached max num, thread parser-001 is ready to exit\n",
      "2025-09-29 23:15:58,194 - INFO - parser - thread parser-001 exit\n"
     ]
    }
   ],
   "source": [
    "NUMBER_OF_IMAGES = 10\n",
    "for bush in bushes:\n",
    "    save_dir = WEB_DATASET_DIR / bush\n",
    "    save_dir.mkdir(exist_ok=True, parents=True)\n",
    "    download_images(f\"куст {bush} реальное фото\", NUMBER_OF_IMAGES, save_dir)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "077870bd",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
